name: "Get Repository Name"
description: "Get the repository name with or without the owner name"
inputs:
  with-owner:
    description: "The owner name should be added in the repository name ?"
    required: false
    default: "false"
outputs:
  repository-name:
    description: "The name of the repository"
runs:
  using: "node16"
  main: "index.js"
