name: Production Deployment

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      tag:
        description: Tag to deploy
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest

    outputs:
      tag: ${{ steps.get-tag.outputs.tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get tag version
        id: get-tag
        uses: wyrihaximus/github-action-get-previous-tag@v1
        with:
          fallback: ${{ inputs.tag }}

  develop-branch:
    needs: [setup]
    uses: ./.github/workflows/rebase_to_master.yml
    with:
      branch_name: "develop"
